server:
  port: 8080
logging:
  level:
    root: debug
  file:
    path: /var/log
    name: api.log

spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    rest:
      uris: 127.0.0.1:9200