
spring:
  application:
    name: product-module
  zipkin:
    base-url: http://localhost:9411
    #取样率 1.0表示百分之百的取样率
    sleuth:
      sampler:
        percentage: 1.0
server:
  port: 8070
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: info
#dubbo
dubbo:
  protocol:
    host: 192.168.1.2
  application:
    name: dubbo-product
  #把本组件的dubbo接口注册到注册中心，从注册中心取其他dubbo接口
  registry:
    address: zookeeper://127.0.0.1:2181
  monitor:
    protocol: registry
  # dubbo使用traceId  关键配置
  provider:
    filter: tracing
  consumer:
    filter: tracing
